# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b5512d1495562111cc21a1e840a692dc342c4fcec799682b88fc686872dc9bdbb56d49b29d4d50bd19758341136b7c28366bb499875dd36d7e0df750039e52

test:
  secret_key_base: 5edd64d68232d5895d1cab70a931a73e2aa2e42c62a8e08dd9e049f788b7afe9717f62ddfb6601c37be935f0df81b0df5673b5d9f26805b4daa0d0c7d848a46e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
